### ISSUE TITLE
Location pin details tooltip/card incorrectly placed on map.

### ISSUE THREAD

**Issue by patricknowlan** [540co/epa-rfi#115]
On the facilities list page, the tooltip gets pulled to the top left corner of the map. It should be located directly above the location pin.

<img width="1005" alt="screen shot 2015-12-29 at 10 32 02 am" src="https://cloud.githubusercontent.com/assets/6303436/12036825/8b2a0e80-ae17-11e5-891c-da8e5230d7d5.png">

**Comment by ostranme** [comment]
https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/docs/info-window.html

NOTE: this directive should NOT be used with ng-repeat because InfoWindow itself is a template, and a template must be reused by each marker, thus, should not be redefined repeatedly by ng-repeat.

Unfortunately we are using ng-repeat for the facility address.
