### ISSUE TITLE
Static page about TRI and information / disclaimer language

### ISSUE THREAD

**Issue by patricknowlan** [540co/epa-rfi#85]

**Comment by pcbock** [comment]
1 - What is the Toxic Release Inventory?

The Toxics Release Inventory (TRI) is a dataset compiled by the U.S. Environmental Protection Agency (EPA). It contains information on toxic chemicals handled by many facilities across the United States, including details on quantities of chemicals managed through disposal or other release, recycling, energy recovery or treatment.

2 - TRI Data goes back to 1987.  Why does Air Hound only include data back to 1998?

Beginning in Reporting Year 1998, TRI reporting was expended to include seven new industries.  Those industries are:
o Metal mining
o Coal mining
o Electric utilities
o Chemical wholesale distributors
o Petroleum bulk storage/terminals
o Hazardous waste management facilities
o Solvent recovery facilities

As a result, the number of TRI records jumps up considerably when you compare 1997 with 1998.  This might give the false impression that toxic releases increased significantly over this period, when in actuality increased number of reports significantly impacts the data.  In order to present a more accurate depiction of toxic release production (and reduction) over time, Air Hound only presents data after this reporting change was made.

However, the APIs Air Hound uses (developed by 540.co) do enable users to access TRI data as far back as 1987.

3 - Where can I find more information?

People often want to use TRI to assess the vulnerability of their communities to the hazards posed by TRI chemicals released in their neighborhoods. When conducting exposure and risk analysis for a community, it is important to keep in mind that:
1. TRI releases do not necessarily constitute cause for concern
2. EPA works to decrease the potential for harm from exposure to toxic chemicals, and
3. Additional resources and information for assessing releases to a community are available.

TRI provides useful information on the quantity of a toxic chemical that is being released from a facility. However, it does not provide all the information necessary to answer questions about health risks. The two main considerations to keep in mind when exploring TRI release information and health risks are
o TRI data only provide information on releases of certain chemicals from certain sources.
o  More information and analyses are needed to determine an individual’s risk associated with TRI releases

For more information on the TRI Program, visit:

http://www.epa.gov/toxics-release-inventory-tri-program
